/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.primaryschoolmanagement.mypackage;



import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author user
 */
public class AdminUserInterface extends javax.swing.JFrame {

    /**
     * Creates new form LibrarianLogin
     */
    public AdminUserInterface() {
      
        initComponents(); 
        connect();
      //  tableLoad();
        
    }
    
    Connection con ;
    PreparedStatement login , pst;
    
    public void connect(){
        try {
            Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost/PrimarySchool","root","");
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(AdminUserInterface.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(AdminUserInterface.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }
    
   /* public void tableLoad() {
        
        try {
            pst = con.prepareStatement("select * from TeacherList");
            ResultSet rs = pst.executeQuery();
            ResultSetMetaData rss = rs.getMetaData();
            DefaultTableModel df = (DefaultTableModel) TeacherTable.getModel();
            df.setRowCount(0);
            while (rs.next()) {   
                
                String id = String.valueOf(rs.getInt("id"));
                String nameString = rs.getString("name");
                String emailString = rs.getString("email");
                String phoneString = rs.getString("phone");
                String positionString = rs.getString("position");
                 
                String tbData[] = {id,nameString,emailString,phoneString,positionString};
                df.addRow(tbData);
                
            }
        } catch (SQLException ex) {
            Logger.getLogger(SyllabusInterface.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }
    */

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        ChangeSyllabusBtn = new javax.swing.JButton();
        LogoutBtn = new javax.swing.JButton();
        PostNoticeBtn = new javax.swing.JButton();
        NoticeBtn = new javax.swing.JButton();
        ResetPassBtn = new javax.swing.JButton();
        teacherBtn = new javax.swing.JButton();
        StudentBtn = new javax.swing.JButton();
        ResultPublishBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAutoRequestFocus(false);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(70, 72, 235));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setIcon(new javax.swing.ImageIcon("/home/rakibul/Pictures/newLogo.png")); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 90, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 340, 380));

        jPanel2.setBackground(new java.awt.Color(254, 254, 254));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ChangeSyllabusBtn.setBackground(new java.awt.Color(70, 72, 235));
        ChangeSyllabusBtn.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        ChangeSyllabusBtn.setForeground(new java.awt.Color(254, 254, 254));
        ChangeSyllabusBtn.setText("Change Syllabus");
        ChangeSyllabusBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ChangeSyllabusBtnMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ChangeSyllabusBtnMouseEntered(evt);
            }
        });
        ChangeSyllabusBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChangeSyllabusBtnActionPerformed(evt);
            }
        });
        jPanel2.add(ChangeSyllabusBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 140, 40));

        LogoutBtn.setBackground(new java.awt.Color(70, 72, 235));
        LogoutBtn.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        LogoutBtn.setForeground(new java.awt.Color(254, 254, 254));
        LogoutBtn.setText("Logout");
        LogoutBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                LogoutBtnMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                LogoutBtnMouseEntered(evt);
            }
        });
        LogoutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogoutBtnActionPerformed(evt);
            }
        });
        jPanel2.add(LogoutBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 240, 140, 40));

        PostNoticeBtn.setBackground(new java.awt.Color(70, 72, 235));
        PostNoticeBtn.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        PostNoticeBtn.setForeground(new java.awt.Color(254, 254, 254));
        PostNoticeBtn.setText("Post Notice");
        PostNoticeBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                PostNoticeBtnMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                PostNoticeBtnMouseEntered(evt);
            }
        });
        PostNoticeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PostNoticeBtnActionPerformed(evt);
            }
        });
        jPanel2.add(PostNoticeBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 60, 140, 40));

        NoticeBtn.setBackground(new java.awt.Color(70, 72, 235));
        NoticeBtn.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        NoticeBtn.setForeground(new java.awt.Color(254, 254, 254));
        NoticeBtn.setText("Notice");
        NoticeBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                NoticeBtnMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                NoticeBtnMouseEntered(evt);
            }
        });
        NoticeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NoticeBtnActionPerformed(evt);
            }
        });
        jPanel2.add(NoticeBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 140, 40));

        ResetPassBtn.setBackground(new java.awt.Color(70, 72, 235));
        ResetPassBtn.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        ResetPassBtn.setForeground(new java.awt.Color(254, 254, 254));
        ResetPassBtn.setText("Reset Password");
        ResetPassBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ResetPassBtnMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ResetPassBtnMouseEntered(evt);
            }
        });
        ResetPassBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResetPassBtnActionPerformed(evt);
            }
        });
        jPanel2.add(ResetPassBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 120, 140, 40));

        teacherBtn.setBackground(new java.awt.Color(70, 72, 235));
        teacherBtn.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        teacherBtn.setForeground(new java.awt.Color(254, 254, 254));
        teacherBtn.setText("Teacher");
        teacherBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                teacherBtnMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                teacherBtnMouseEntered(evt);
            }
        });
        teacherBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                teacherBtnActionPerformed(evt);
            }
        });
        jPanel2.add(teacherBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 140, 40));

        StudentBtn.setBackground(new java.awt.Color(70, 72, 235));
        StudentBtn.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        StudentBtn.setForeground(new java.awt.Color(254, 254, 254));
        StudentBtn.setText("Student");
        StudentBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                StudentBtnMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                StudentBtnMouseEntered(evt);
            }
        });
        StudentBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StudentBtnActionPerformed(evt);
            }
        });
        jPanel2.add(StudentBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 180, 140, 40));

        ResultPublishBtn.setBackground(new java.awt.Color(70, 72, 235));
        ResultPublishBtn.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        ResultPublishBtn.setForeground(new java.awt.Color(254, 254, 254));
        ResultPublishBtn.setText("Result");
        ResultPublishBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ResultPublishBtnMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ResultPublishBtnMouseEntered(evt);
            }
        });
        ResultPublishBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResultPublishBtnActionPerformed(evt);
            }
        });
        jPanel2.add(ResultPublishBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, 140, 40));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 0, 380, 390));

        setSize(new java.awt.Dimension(704, 401));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ChangeSyllabusBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ChangeSyllabusBtnMouseExited
        // TODO add your handling code here:

        ChangeSyllabusBtn.setBackground(Color.decode("#4648eb"));
    }//GEN-LAST:event_ChangeSyllabusBtnMouseExited

    private void ChangeSyllabusBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ChangeSyllabusBtnMouseEntered
        // TODO add your handling code here:
        ChangeSyllabusBtn.setBackground(Color.decode("#1417f2"));
    }//GEN-LAST:event_ChangeSyllabusBtnMouseEntered

    private void ChangeSyllabusBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChangeSyllabusBtnActionPerformed
        // TODO add your handling code here:
        new ChangeSyllabus().setVisible(true);
        this.setVisible(false);

    }//GEN-LAST:event_ChangeSyllabusBtnActionPerformed

    private void LogoutBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogoutBtnMouseExited
        // TODO add your handling code here:
        LogoutBtn.setBackground(Color.decode("#4648eb"));
    }//GEN-LAST:event_LogoutBtnMouseExited

    private void LogoutBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogoutBtnMouseEntered
        // TODO add your handling code here:
        LogoutBtn.setBackground(Color.decode("#1417f2"));
    }//GEN-LAST:event_LogoutBtnMouseEntered

    private void LogoutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogoutBtnActionPerformed
        // TODO add your handling code here:
        new MainUserInterface().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_LogoutBtnActionPerformed

    private void PostNoticeBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PostNoticeBtnMouseExited
        // TODO add your handling code here:
        PostNoticeBtn.setBackground(Color.decode("#4648eb"));
    }//GEN-LAST:event_PostNoticeBtnMouseExited

    private void PostNoticeBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PostNoticeBtnMouseEntered
        // TODO add your handling code here:
        PostNoticeBtn.setBackground(Color.decode("#1417f2"));
    }//GEN-LAST:event_PostNoticeBtnMouseEntered

    private void PostNoticeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PostNoticeBtnActionPerformed
        // TODO add your handling code here:
        new PostNotice().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_PostNoticeBtnActionPerformed

    private void NoticeBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NoticeBtnMouseExited
        // TODO add your handling code here:
        NoticeBtn.setBackground(Color.decode("#4648eb"));
    }//GEN-LAST:event_NoticeBtnMouseExited

    private void NoticeBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NoticeBtnMouseEntered
        // TODO add your handling code here:
        NoticeBtn.setBackground(Color.decode("#1417f2"));
    }//GEN-LAST:event_NoticeBtnMouseEntered

    private void NoticeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NoticeBtnActionPerformed
        // TODO add your handling code here:
        new AdminNoticeList().setVisible(true);
        this.setVisible(false);
        
    }//GEN-LAST:event_NoticeBtnActionPerformed

    private void ResetPassBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ResetPassBtnMouseExited
        // TODO add your handling code here:
          ResetPassBtn.setBackground(Color.decode("#4648eb"));
          
         
    }//GEN-LAST:event_ResetPassBtnMouseExited

    private void ResetPassBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ResetPassBtnMouseEntered
        // TODO add your handling code here:
          ResetPassBtn.setBackground(Color.decode("#1417f2"));
    }//GEN-LAST:event_ResetPassBtnMouseEntered

    private void ResetPassBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResetPassBtnActionPerformed
        // TODO add your handling code here:
        new ResetPassword().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_ResetPassBtnActionPerformed

    private void teacherBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_teacherBtnMouseExited
        // TODO add your handling code here:
        teacherBtn.setBackground(Color.decode("#4648eb"));
        
    }//GEN-LAST:event_teacherBtnMouseExited

    private void teacherBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_teacherBtnMouseEntered
        // TODO add your handling code here:
        teacherBtn.setBackground(Color.decode("#1417f2"));
    }//GEN-LAST:event_teacherBtnMouseEntered

    private void teacherBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_teacherBtnActionPerformed
        // TODO add your handling code here:
        new TeacherUpdate().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_teacherBtnActionPerformed

    private void StudentBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_StudentBtnMouseExited
        // TODO add your handling code here:
        StudentBtn.setBackground(Color.decode("#4648eb"));
 
    }//GEN-LAST:event_StudentBtnMouseExited

    private void StudentBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_StudentBtnMouseEntered
        // TODO add your handling code here:
        StudentBtn.setBackground(Color.decode("#1417f2"));
    }//GEN-LAST:event_StudentBtnMouseEntered

    private void StudentBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StudentBtnActionPerformed
        // TODO add your handling code here:
        new StudentUpdate().setVisible(true);
        this.setVisible(false);
        
    }//GEN-LAST:event_StudentBtnActionPerformed

    private void ResultPublishBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ResultPublishBtnMouseExited
        // TODO add your handling code here:
        ResultPublishBtn.setBackground(Color.decode("#4648eb"));
 
    }//GEN-LAST:event_ResultPublishBtnMouseExited

    private void ResultPublishBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ResultPublishBtnMouseEntered
        // TODO add your handling code here:
        ResultPublishBtn.setBackground(Color.decode("#1417f2"));
    }//GEN-LAST:event_ResultPublishBtnMouseEntered

    private void ResultPublishBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResultPublishBtnActionPerformed
        // TODO add your handling code here:
        new ResultPublish().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_ResultPublishBtnActionPerformed
 
    
    
    

    

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminUserInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminUserInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminUserInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminUserInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminUserInterface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ChangeSyllabusBtn;
    private javax.swing.JButton LogoutBtn;
    private javax.swing.JButton NoticeBtn;
    private javax.swing.JButton PostNoticeBtn;
    private javax.swing.JButton ResetPassBtn;
    private javax.swing.JButton ResultPublishBtn;
    private javax.swing.JButton StudentBtn;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton teacherBtn;
    // End of variables declaration//GEN-END:variables
}
