/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.primaryschoolmanagement.mypackage;



import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author user
 */
public class ForgotPassword extends javax.swing.JFrame {

    /**
     * Creates new form LibrarianLogin
     */
    public ForgotPassword() {
      
        initComponents();
        cleanTxt();
        connect();
        
    }
    
    Connection con ;
    PreparedStatement login , pst;
    
    public void connect(){
        try {
            Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost/PrimarySchool","root","");
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(ForgotPassword.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(ForgotPassword.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        GetPassBtn = new javax.swing.JButton();
        cancelBtn = new javax.swing.JButton();
        Q3 = new javax.swing.JTextField();
        Q1 = new javax.swing.JTextField();
        Q2 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAutoRequestFocus(false);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(70, 72, 235));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setIcon(new javax.swing.ImageIcon("/home/rakibul/Pictures/newLogo.png")); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 100, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 340, 410));

        jPanel2.setBackground(new java.awt.Color(254, 254, 254));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        GetPassBtn.setBackground(new java.awt.Color(70, 72, 235));
        GetPassBtn.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        GetPassBtn.setForeground(new java.awt.Color(254, 254, 254));
        GetPassBtn.setText("Show");
        GetPassBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                GetPassBtnMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                GetPassBtnMouseEntered(evt);
            }
        });
        GetPassBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GetPassBtnActionPerformed(evt);
            }
        });
        jPanel2.add(GetPassBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 320, 100, 40));

        cancelBtn.setBackground(new java.awt.Color(70, 72, 235));
        cancelBtn.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        cancelBtn.setForeground(new java.awt.Color(254, 254, 254));
        cancelBtn.setText("Cancel");
        cancelBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                cancelBtnMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cancelBtnMouseEntered(evt);
            }
        });
        cancelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelBtnActionPerformed(evt);
            }
        });
        jPanel2.add(cancelBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 320, 100, 40));

        Q3.setBackground(new java.awt.Color(254, 254, 254));
        Q3.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        Q3.setForeground(new java.awt.Color(70, 72, 235));
        Q3.setBorder(null);
        jPanel2.add(Q3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, 260, 40));

        Q1.setBackground(new java.awt.Color(254, 254, 254));
        Q1.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        Q1.setForeground(new java.awt.Color(70, 72, 235));
        Q1.setBorder(null);
        jPanel2.add(Q1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, 260, 40));

        Q2.setBackground(new java.awt.Color(254, 254, 254));
        Q2.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        Q2.setForeground(new java.awt.Color(70, 72, 235));
        Q2.setBorder(null);
        jPanel2.add(Q2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, 260, 40));

        jLabel1.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(70, 72, 235));
        jLabel1.setText("Your Childhood Hero");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, -1, -1));

        jLabel2.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(70, 72, 235));
        jLabel2.setText("Your First Pet");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, -1, -1));

        jLabel4.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(70, 72, 235));
        jLabel4.setText("Your Favourite Vacation Place");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, -1, -1));
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 290, 260, 10));
        jPanel2.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, 260, 10));
        jPanel2.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, 260, 10));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 0, 360, 410));

        setSize(new java.awt.Dimension(693, 440));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void GetPassBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GetPassBtnMouseEntered
        // TODO add your handling code here:
        GetPassBtn.setBackground(Color.decode("#1417f2"));
    }//GEN-LAST:event_GetPassBtnMouseEntered

    private void GetPassBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GetPassBtnMouseExited
        // TODO add your handling code here:
         GetPassBtn.setBackground(Color.decode("#4648eb"));
    }//GEN-LAST:event_GetPassBtnMouseExited

    private void GetPassBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GetPassBtnActionPerformed
        // TODO add your handling code here:
        try {
            String ans1 = "Tom" , ans2 = "Nazrul" , ans3 = "Rangamati" ;
            int num = 0 ;
            if(Q1.getText().equals(ans1))
                num++;
            if(Q2.getText().equals(ans2))
                num++;
            if(Q3.getText().equals(ans3))
                num++;
            pst = con.prepareStatement("Select password from Admin where id = ?");
            pst.setString(1, "admin");
            ResultSet rs = pst.executeQuery();
            if(Q1.getText().equals("") || Q2.getText().equals("") || Q3.getText().equals("")){
                JOptionPane.showMessageDialog(this, "Please write all the Answers");
                cleanTxt();
            }
            else if(num==3 && rs.next())
            {
                String Pass = rs.getString("password");
                
                JOptionPane.showMessageDialog(this, "Your Password : "+Pass);
                cleanTxt();
            }
            else{
                int wrongAns = 3 - num ;
                String w = String.valueOf(wrongAns);
                if(wrongAns>1)
                JOptionPane.showMessageDialog(this, w+" Wrong Answers Found");
                else
                JOptionPane.showMessageDialog(this, w+" Wrong Answer Found");  
                cleanTxt();
            }
            
        } catch (SQLException exception) {
            JOptionPane.showMessageDialog(this, "Login Failed");
        }
    }//GEN-LAST:event_GetPassBtnActionPerformed

    private void cancelBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelBtnMouseExited
        // TODO add your handling code here:
         
        cancelBtn.setBackground(Color.decode("#4648eb"));
    }//GEN-LAST:event_cancelBtnMouseExited

    private void cancelBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelBtnMouseEntered
        // TODO add your handling code here:
        cancelBtn.setBackground(Color.decode("#1417f2"));
    }//GEN-LAST:event_cancelBtnMouseEntered

    private void cancelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelBtnActionPerformed
        // TODO add your handling code here:
        new AdminLoginPage().setVisible(true);
        this.setVisible(false);
        cleanTxt();
    }//GEN-LAST:event_cancelBtnActionPerformed
 
    
    
    
    public void cleanTxt(){
          Q1.setText("");
          Q2.setText("");
          Q3.setText("");
          
    }
    

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ForgotPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ForgotPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ForgotPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ForgotPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ForgotPassword().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton GetPassBtn;
    private javax.swing.JTextField Q1;
    private javax.swing.JTextField Q2;
    private javax.swing.JTextField Q3;
    private javax.swing.JButton cancelBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    // End of variables declaration//GEN-END:variables
}
