/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.primaryschoolmanagement.mypackage;

import java.awt.Color;

/**
 *
 * @author rakibul
 */
public class MainUserInterface extends javax.swing.JFrame {

    /**
     * Creates new form MainUserInterface
     */
    public MainUserInterface() {
        initComponents();
        //backBtn.setBackground(Color.white);
        MainPanel.setBackground(Color.white);
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        AdminBtn1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        backBtn = new javax.swing.JButton();
        AdminBtn = new javax.swing.JButton();
        TeacherBtn = new javax.swing.JButton();
        TeacherList = new javax.swing.JButton();
        Syllabus = new javax.swing.JButton();
        NoticeBtn = new javax.swing.JButton();
        GuardianBtn = new javax.swing.JButton();
        ResultSearchBtn = new javax.swing.JButton();
        MainPanel = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        jLabel6.setText("jLabel6");

        AdminBtn1.setBackground(new java.awt.Color(71, 160, 241));
        AdminBtn1.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        AdminBtn1.setForeground(new java.awt.Color(254, 254, 254));
        AdminBtn1.setText("Admin");
        AdminBtn1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                AdminBtn1MouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                AdminBtn1MouseEntered(evt);
            }
        });
        AdminBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdminBtn1ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(62, 199, 206));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Z003", 0, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(254, 254, 254));
        jLabel1.setText("MRSS Primary School");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 0, 410, -1));
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 20, -1, -1));

        jLabel3.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(254, 247, 247));
        jLabel3.setText("Education is for everyone");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 40, -1, -1));

        jLabel4.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(251, 246, 246));
        jLabel4.setText("Since 2021");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 50, -1, 40));

        jLabel5.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        jLabel5.setIcon(new javax.swing.ImageIcon("/home/rakibul/Pictures/newLogo_50.png")); // NOI18N
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 0, 100, 90));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 620, 90));

        jPanel2.setBackground(new java.awt.Color(19, 173, 201));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 620, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 620, 10));

        jPanel3.setBackground(new java.awt.Color(30, 148, 189));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED), "Menu", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Z003", 1, 36), new java.awt.Color(254, 247, 247))); // NOI18N

        backBtn.setBackground(new java.awt.Color(71, 160, 241));
        backBtn.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        backBtn.setForeground(new java.awt.Color(254, 254, 254));
        backBtn.setText("Back");
        backBtn.setMaximumSize(new java.awt.Dimension(42, 35));
        backBtn.setMinimumSize(new java.awt.Dimension(42, 35));
        backBtn.setPreferredSize(new java.awt.Dimension(81, 36));
        backBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                backBtnMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                backBtnMouseEntered(evt);
            }
        });
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        AdminBtn.setBackground(new java.awt.Color(71, 160, 241));
        AdminBtn.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        AdminBtn.setForeground(new java.awt.Color(254, 254, 254));
        AdminBtn.setText("Admin");
        AdminBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                AdminBtnMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                AdminBtnMouseEntered(evt);
            }
        });
        AdminBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdminBtnActionPerformed(evt);
            }
        });

        TeacherBtn.setBackground(new java.awt.Color(71, 160, 241));
        TeacherBtn.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        TeacherBtn.setForeground(new java.awt.Color(254, 254, 254));
        TeacherBtn.setText("Teacher");
        TeacherBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                TeacherBtnMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                TeacherBtnMouseEntered(evt);
            }
        });
        TeacherBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TeacherBtnActionPerformed(evt);
            }
        });

        TeacherList.setBackground(new java.awt.Color(71, 160, 241));
        TeacherList.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        TeacherList.setForeground(new java.awt.Color(254, 254, 254));
        TeacherList.setText("Teacher List");
        TeacherList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                TeacherListMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                TeacherListMouseEntered(evt);
            }
        });
        TeacherList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TeacherListActionPerformed(evt);
            }
        });

        Syllabus.setBackground(new java.awt.Color(71, 160, 241));
        Syllabus.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        Syllabus.setForeground(new java.awt.Color(254, 254, 254));
        Syllabus.setText("Syllabus");
        Syllabus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                SyllabusMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                SyllabusMouseEntered(evt);
            }
        });
        Syllabus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SyllabusActionPerformed(evt);
            }
        });

        NoticeBtn.setBackground(new java.awt.Color(71, 160, 241));
        NoticeBtn.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        NoticeBtn.setForeground(new java.awt.Color(254, 254, 254));
        NoticeBtn.setText("Notice");
        NoticeBtn.setMaximumSize(new java.awt.Dimension(42, 35));
        NoticeBtn.setMinimumSize(new java.awt.Dimension(42, 35));
        NoticeBtn.setPreferredSize(new java.awt.Dimension(81, 36));
        NoticeBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                NoticeBtnMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                NoticeBtnMouseEntered(evt);
            }
        });
        NoticeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NoticeBtnActionPerformed(evt);
            }
        });

        GuardianBtn.setBackground(new java.awt.Color(71, 160, 241));
        GuardianBtn.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        GuardianBtn.setForeground(new java.awt.Color(254, 254, 254));
        GuardianBtn.setText("Guardian");
        GuardianBtn.setMaximumSize(new java.awt.Dimension(42, 35));
        GuardianBtn.setMinimumSize(new java.awt.Dimension(42, 35));
        GuardianBtn.setPreferredSize(new java.awt.Dimension(81, 36));
        GuardianBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                GuardianBtnMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                GuardianBtnMouseEntered(evt);
            }
        });
        GuardianBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GuardianBtnActionPerformed(evt);
            }
        });

        ResultSearchBtn.setBackground(new java.awt.Color(71, 160, 241));
        ResultSearchBtn.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        ResultSearchBtn.setForeground(new java.awt.Color(254, 254, 254));
        ResultSearchBtn.setText("Result Search");
        ResultSearchBtn.setMaximumSize(new java.awt.Dimension(42, 35));
        ResultSearchBtn.setMinimumSize(new java.awt.Dimension(42, 35));
        ResultSearchBtn.setPreferredSize(new java.awt.Dimension(81, 36));
        ResultSearchBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ResultSearchBtnMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ResultSearchBtnMouseEntered(evt);
            }
        });
        ResultSearchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResultSearchBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(AdminBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 176, Short.MAX_VALUE)
            .addComponent(TeacherBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(TeacherList, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(Syllabus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(backBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(ResultSearchBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(NoticeBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(GuardianBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 176, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addComponent(AdminBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TeacherBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TeacherList, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Syllabus, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(NoticeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ResultSearchBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(GuardianBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(backBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 190, 390));

        MainPanel.setBackground(new java.awt.Color(254, 254, 254));
        MainPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setIcon(new javax.swing.ImageIcon("/home/rakibul/Pictures/newLogoDark_50.png")); // NOI18N
        MainPanel.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 100, 100));

        jLabel8.setFont(new java.awt.Font("Ubuntu", 3, 14)); // NOI18N
        jLabel8.setText("Message");
        MainPanel.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 40, 70, 30));

        jLabel9.setIcon(new javax.swing.ImageIcon("/home/rakibul/Pictures/headphtoto_25.png")); // NOI18N
        MainPanel.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 10, 70, 80));

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Ubuntu Light", 0, 12)); // NOI18N
        jTextArea1.setRows(5);
        jTextArea1.setText("Knowledge is power but nowadays it is thought, information technology \n(IT)  is power. Those who \nprocess more information are more knowledgeable. By browsing internet, we can communicate with \nthe whole world. The world seems to be a global village. We can know very rapidly what is \nhappening throughout the world.\n\nIn the age of modern technology computer creates a vital role on academic activities.Publishing \nresults and providing all kinds of relevant activities become easy to easier. A student \ncan get necessary information with in a few times. Reading becomes more interesting and informative.\n\nMRSS Primary School is going to introduce the modern technology for the betterment of all \nconcern.I think this step is helpful to its all activities .I wish its overall success and Continuity.\n\n\nMd. Kamal Uddin\nHeadmaster,\nMRSS Primary School,\nChittagong."); // NOI18N
        jTextArea1.setCaretColor(new java.awt.Color(8, 1, 1));
        jTextArea1.setCaretPosition(0);
        jTextArea1.setDragEnabled(true);
        jScrollPane1.setViewportView(jTextArea1);

        MainPanel.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 390, 290));

        getContentPane().add(MainPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 100, 430, 400));

        setSize(new java.awt.Dimension(616, 533));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void backBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backBtnMouseEntered
        // TODO add your handling code here:
        backBtn.setBackground(Color.decode("#1417f2"));
        
    }//GEN-LAST:event_backBtnMouseEntered

    private void backBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backBtnMouseExited
        // TODO add your handling code here:
        backBtn.setBackground(Color.decode("#47a0f1"));
    }//GEN-LAST:event_backBtnMouseExited

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:
        new OpeningPage().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_backBtnActionPerformed

    private void AdminBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AdminBtnMouseExited
        // TODO add your handling code here:
        AdminBtn.setBackground(Color.decode("#47a0f1"));
    }//GEN-LAST:event_AdminBtnMouseExited

    private void AdminBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AdminBtnMouseEntered
        // TODO add your handling code here:
        AdminBtn.setBackground(Color.decode("#1417f2"));
    }//GEN-LAST:event_AdminBtnMouseEntered

    private void AdminBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdminBtnActionPerformed
        // TODO add your handling code here:
        new AdminLoginPage().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_AdminBtnActionPerformed

    private void AdminBtn1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AdminBtn1MouseExited
        // TODO add your handling code here:
         
        AdminBtn1.setBackground(Color.decode("#47a0f1"));
    }//GEN-LAST:event_AdminBtn1MouseExited

    private void AdminBtn1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AdminBtn1MouseEntered
        // TODO add your handling code here:
        AdminBtn1.setBackground(Color.decode("#1417f2"));
    }//GEN-LAST:event_AdminBtn1MouseEntered

    private void AdminBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdminBtn1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AdminBtn1ActionPerformed

    private void TeacherBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TeacherBtnMouseExited
        // TODO add your handling code here:
         TeacherBtn.setBackground(Color.decode("#47a0f1"));
    }//GEN-LAST:event_TeacherBtnMouseExited

    private void TeacherBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TeacherBtnMouseEntered
        // TODO add your handling code here:
        TeacherBtn.setBackground(Color.decode("#1417f2"));
    }//GEN-LAST:event_TeacherBtnMouseEntered

    private void TeacherBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TeacherBtnActionPerformed
        // TODO add your handling code here:
        new TeacherLogin().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_TeacherBtnActionPerformed

    private void TeacherListMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TeacherListMouseExited
        // TODO add your handling code here:
         TeacherList.setBackground(Color.decode("#47a0f1"));
    }//GEN-LAST:event_TeacherListMouseExited

    private void TeacherListMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TeacherListMouseEntered
        // TODO add your handling code here:
        TeacherList.setBackground(Color.decode("#1417f2"));
    }//GEN-LAST:event_TeacherListMouseEntered

    private void TeacherListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TeacherListActionPerformed
        // TODO add your handling code here:
        new TeacherList().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_TeacherListActionPerformed

    private void SyllabusMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SyllabusMouseExited
        // TODO add your handling code here:
         Syllabus.setBackground(Color.decode("#47a0f1"));
    }//GEN-LAST:event_SyllabusMouseExited

    private void SyllabusMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SyllabusMouseEntered
        // TODO add your handling code here:
        Syllabus.setBackground(Color.decode("#1417f2"));
    }//GEN-LAST:event_SyllabusMouseEntered

    private void SyllabusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SyllabusActionPerformed
        // TODO add your handling code here:
        new SyllabusInterface().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_SyllabusActionPerformed

    private void NoticeBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NoticeBtnMouseExited
        // TODO add your handling code here:
        NoticeBtn.setBackground(Color.decode("#47a0f1"));
    }//GEN-LAST:event_NoticeBtnMouseExited

    private void NoticeBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NoticeBtnMouseEntered
        // TODO add your handling code here:
        NoticeBtn.setBackground(Color.decode("#1417f2"));
    }//GEN-LAST:event_NoticeBtnMouseEntered

    private void NoticeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NoticeBtnActionPerformed
        // TODO add your handling code here:
        new NoticeList().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_NoticeBtnActionPerformed

    private void GuardianBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GuardianBtnMouseExited
        // TODO add your handling code here:
         GuardianBtn.setBackground(Color.decode("#47a0f1"));
    }//GEN-LAST:event_GuardianBtnMouseExited

    private void GuardianBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GuardianBtnMouseEntered
        // TODO add your handling code here:
        GuardianBtn.setBackground(Color.decode("#1417f2"));
    }//GEN-LAST:event_GuardianBtnMouseEntered

    private void GuardianBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuardianBtnActionPerformed
        // TODO add your handling code here:
        new GuardianLoginPage().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_GuardianBtnActionPerformed

    private void ResultSearchBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ResultSearchBtnMouseExited
        // TODO add your handling code here:
         ResultSearchBtn.setBackground(Color.decode("#47a0f1"));
    }//GEN-LAST:event_ResultSearchBtnMouseExited

    private void ResultSearchBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ResultSearchBtnMouseEntered
        // TODO add your handling code here:
        ResultSearchBtn.setBackground(Color.decode("#1417f2"));
    }//GEN-LAST:event_ResultSearchBtnMouseEntered

    private void ResultSearchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResultSearchBtnActionPerformed
        // TODO add your handling code here:
        new ResultSearch().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_ResultSearchBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainUserInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainUserInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainUserInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainUserInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainUserInterface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AdminBtn;
    private javax.swing.JButton AdminBtn1;
    private javax.swing.JButton GuardianBtn;
    private javax.swing.JPanel MainPanel;
    private javax.swing.JButton NoticeBtn;
    private javax.swing.JButton ResultSearchBtn;
    private javax.swing.JButton Syllabus;
    private javax.swing.JButton TeacherBtn;
    private javax.swing.JButton TeacherList;
    private javax.swing.JButton backBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
