/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.primaryschoolmanagement.mypackage;



import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author user
 */
public class ResultPublish extends javax.swing.JFrame {

    /**
     * Creates new form LibrarianLogin
     */
    public ResultPublish() {
      
        initComponents(); 
        clearTxt();
        connect();
        tableLoad();
        IDLoad();
    }
    
    Connection con ;
    PreparedStatement login , pst , add , update , delete;
    String id;
    
    public void connect(){
        try {
            Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost/PrimarySchool","root","");
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(ResultPublish.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(ResultPublish.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator1 = new javax.swing.JSeparator();
        cancelBtn = new javax.swing.JButton();
        AddBtn = new javax.swing.JButton();
        deleteBtn = new javax.swing.JButton();
        mathTxt = new javax.swing.JTextField();
        englishTxt = new javax.swing.JTextField();
        socialTxt = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        banglaTxt = new javax.swing.JTextField();
        jSeparator6 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        updateBtn = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        scienceTxt = new javax.swing.JTextField();
        religionTxt = new javax.swing.JTextField();
        jSeparator8 = new javax.swing.JSeparator();
        jSeparator9 = new javax.swing.JSeparator();
        termBox = new javax.swing.JComboBox<>();
        stdIDBox = new javax.swing.JComboBox<>();
        yearBox = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        searchTxt = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TeacherTable = new javax.swing.JTable();
        jSeparator7 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAutoRequestFocus(false);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(102, 197, 240));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jSeparator2.setBackground(java.awt.Color.black);
        jPanel2.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 140, 210, -1));

        jSeparator1.setForeground(new java.awt.Color(2, 39, 241));
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 260, 210, 10));

        cancelBtn.setBackground(new java.awt.Color(70, 72, 235));
        cancelBtn.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        cancelBtn.setForeground(new java.awt.Color(254, 254, 254));
        cancelBtn.setText("Cancel");
        cancelBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                cancelBtnMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cancelBtnMouseEntered(evt);
            }
        });
        cancelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelBtnActionPerformed(evt);
            }
        });
        jPanel2.add(cancelBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 550, 100, 40));

        AddBtn.setBackground(new java.awt.Color(70, 72, 235));
        AddBtn.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        AddBtn.setForeground(new java.awt.Color(254, 254, 254));
        AddBtn.setText("Add");
        AddBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                AddBtnMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                AddBtnMouseEntered(evt);
            }
        });
        AddBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddBtnActionPerformed(evt);
            }
        });
        jPanel2.add(AddBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 500, 100, 40));

        deleteBtn.setBackground(new java.awt.Color(70, 72, 235));
        deleteBtn.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        deleteBtn.setForeground(new java.awt.Color(254, 254, 254));
        deleteBtn.setText("Delete");
        deleteBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                deleteBtnMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                deleteBtnMouseEntered(evt);
            }
        });
        deleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBtnActionPerformed(evt);
            }
        });
        jPanel2.add(deleteBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 550, 100, 40));

        mathTxt.setBackground(new java.awt.Color(254, 254, 254));
        mathTxt.setFont(new java.awt.Font("URW Bookman L", 1, 14)); // NOI18N
        mathTxt.setForeground(new java.awt.Color(70, 72, 235));
        mathTxt.setBorder(null);
        mathTxt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                mathTxtFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                mathTxtFocusLost(evt);
            }
        });
        mathTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                mathTxtMousePressed(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mathTxtMouseClicked(evt);
            }
        });
        mathTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mathTxtActionPerformed(evt);
            }
        });
        jPanel2.add(mathTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 270, 210, 40));

        englishTxt.setBackground(new java.awt.Color(254, 254, 254));
        englishTxt.setFont(new java.awt.Font("URW Bookman L", 1, 14)); // NOI18N
        englishTxt.setForeground(new java.awt.Color(70, 72, 235));
        englishTxt.setBorder(null);
        englishTxt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                englishTxtFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                englishTxtFocusLost(evt);
            }
        });
        englishTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                englishTxtMousePressed(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                englishTxtMouseClicked(evt);
            }
        });
        englishTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                englishTxtActionPerformed(evt);
            }
        });
        jPanel2.add(englishTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 220, 210, 40));

        socialTxt.setBackground(new java.awt.Color(254, 254, 254));
        socialTxt.setFont(new java.awt.Font("URW Bookman L", 1, 14)); // NOI18N
        socialTxt.setForeground(new java.awt.Color(70, 72, 235));
        socialTxt.setBorder(null);
        socialTxt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                socialTxtFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                socialTxtFocusLost(evt);
            }
        });
        socialTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                socialTxtMousePressed(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                socialTxtMouseClicked(evt);
            }
        });
        socialTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                socialTxtActionPerformed(evt);
            }
        });
        jPanel2.add(socialTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 420, 210, 40));

        jSeparator4.setForeground(new java.awt.Color(2, 39, 241));
        jPanel2.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 310, 210, 10));

        jSeparator5.setForeground(new java.awt.Color(2, 39, 241));
        jPanel2.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 460, 210, 20));

        banglaTxt.setBackground(new java.awt.Color(254, 254, 254));
        banglaTxt.setFont(new java.awt.Font("URW Bookman L", 1, 14)); // NOI18N
        banglaTxt.setForeground(new java.awt.Color(70, 72, 235));
        banglaTxt.setBorder(null);
        banglaTxt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                banglaTxtFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                banglaTxtFocusLost(evt);
            }
        });
        banglaTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                banglaTxtMousePressed(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                banglaTxtMouseClicked(evt);
            }
        });
        banglaTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                banglaTxtActionPerformed(evt);
            }
        });
        jPanel2.add(banglaTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 170, 210, 40));

        jSeparator6.setForeground(new java.awt.Color(2, 39, 241));
        jPanel2.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 210, 210, 10));

        jLabel6.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(251, 246, 246));
        jLabel6.setText("Social Science");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 420, -1, 40));

        jLabel10.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(251, 246, 246));
        jLabel10.setText("Student ID");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, -1, 40));

        jLabel11.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(251, 246, 246));
        jLabel11.setText("Year");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, -1, 40));

        jLabel12.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(251, 246, 246));
        jLabel12.setText("Term");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, -1, 40));

        jLabel13.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(251, 246, 246));
        jLabel13.setText("Bangla");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, -1, 40));

        updateBtn.setBackground(new java.awt.Color(70, 72, 235));
        updateBtn.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        updateBtn.setForeground(new java.awt.Color(254, 254, 254));
        updateBtn.setText("Update");
        updateBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                updateBtnMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                updateBtnMouseEntered(evt);
            }
        });
        updateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateBtnActionPerformed(evt);
            }
        });
        jPanel2.add(updateBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 500, 100, 40));

        jLabel14.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(251, 246, 246));
        jLabel14.setText("English");
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, -1, 40));

        jLabel15.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(251, 246, 246));
        jLabel15.setText("Math");
        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, -1, 40));

        jLabel16.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(251, 246, 246));
        jLabel16.setText("Science");
        jPanel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 320, -1, 40));

        jLabel17.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(251, 246, 246));
        jLabel17.setText("Religion");
        jPanel2.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 370, -1, 40));

        scienceTxt.setBackground(new java.awt.Color(254, 254, 254));
        scienceTxt.setFont(new java.awt.Font("URW Bookman L", 1, 14)); // NOI18N
        scienceTxt.setForeground(new java.awt.Color(70, 72, 235));
        scienceTxt.setBorder(null);
        scienceTxt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                scienceTxtFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                scienceTxtFocusLost(evt);
            }
        });
        scienceTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                scienceTxtMousePressed(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                scienceTxtMouseClicked(evt);
            }
        });
        scienceTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                scienceTxtActionPerformed(evt);
            }
        });
        jPanel2.add(scienceTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 320, 210, 40));

        religionTxt.setBackground(new java.awt.Color(254, 254, 254));
        religionTxt.setFont(new java.awt.Font("URW Bookman L", 1, 14)); // NOI18N
        religionTxt.setForeground(new java.awt.Color(70, 72, 235));
        religionTxt.setBorder(null);
        religionTxt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                religionTxtFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                religionTxtFocusLost(evt);
            }
        });
        religionTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                religionTxtMousePressed(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                religionTxtMouseClicked(evt);
            }
        });
        religionTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                religionTxtActionPerformed(evt);
            }
        });
        jPanel2.add(religionTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 370, 210, 40));

        jSeparator8.setForeground(new java.awt.Color(2, 39, 241));
        jPanel2.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 360, 210, 20));

        jSeparator9.setForeground(new java.awt.Color(2, 39, 241));
        jPanel2.add(jSeparator9, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 410, 210, 20));

        termBox.setBackground(new java.awt.Color(254, 254, 254));
        termBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mid-Term", "Final" }));
        termBox.setSelectedIndex(-1);
        jPanel2.add(termBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 130, 210, -1));

        stdIDBox.setBackground(new java.awt.Color(254, 254, 254));
        stdIDBox.setSelectedIndex(-1);
        jPanel2.add(stdIDBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 30, 210, -1));

        yearBox.setBackground(new java.awt.Color(254, 254, 254));
        yearBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2021", "2022", "2023", "2024" }));
        yearBox.setSelectedIndex(-1);
        jPanel2.add(yearBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 80, 210, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 100, 360, 650));

        jPanel1.setBackground(new java.awt.Color(62, 199, 206));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Z003", 0, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(254, 254, 254));
        jLabel1.setText("MRSS Primary School");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 0, 410, -1));

        jLabel3.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(254, 247, 247));
        jLabel3.setText("Education is for everyone");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 40, -1, -1));

        jLabel7.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        jLabel7.setIcon(new javax.swing.ImageIcon("/home/rakibul/Pictures/newLogo_50.png")); // NOI18N
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 0, 100, 90));

        jLabel9.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(251, 246, 246));
        jLabel9.setText("Since 2021");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 50, -1, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 780, 90));

        jPanel3.setBackground(new java.awt.Color(19, 173, 201));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 780, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 780, 10));

        jLabel8.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(251, 246, 246));
        jLabel8.setText("Since 2021");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 50, -1, 40));

        jPanel4.setBackground(new java.awt.Color(254, 254, 254));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        searchTxt.setBackground(new java.awt.Color(254, 254, 254));
        searchTxt.setBorder(null);
        searchTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchTxtActionPerformed(evt);
            }
        });
        searchTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                searchTxtKeyReleased(evt);
            }
        });
        jPanel4.add(searchTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, 360, 30));

        jLabel2.setIcon(new javax.swing.ImageIcon("/home/rakibul/Pictures/Search_30x30.jpg")); // NOI18N
        jPanel4.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 30, 30));

        TeacherTable.setBackground(new java.awt.Color(254, 254, 254));
        TeacherTable.setFont(new java.awt.Font("Ubuntu", 1, 12)); // NOI18N
        TeacherTable.setForeground(new java.awt.Color(70, 72, 235));
        TeacherTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Year", "Term", "Bangla", "English", "Math", "Science", "Religion", "Social Science"
            }
        ));
        TeacherTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TeacherTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TeacherTable);

        jPanel4.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 390, 440));
        jPanel4.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, 360, 10));

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 100, 440, 650));

        setSize(new java.awt.Dimension(779, 750));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    
       public void IDLoad(){
        try {
            pst = (PreparedStatement) con.prepareStatement("SELECT id FROM StudentList");
            ResultSet rs = pst.executeQuery();
            while (rs.next()) {
                
                String CatItem = rs.getString("id");
                
                stdIDBox.addItem(CatItem);
                
                
                
            }
        } catch (SQLException ex) {
            Logger.getLogger(ResultPublish.class.getName()).log(Level.SEVERE, null, ex);
        }
       }
       public void tableLoad() {
        
        try {
            pst = con.prepareStatement("select * from Result");
            ResultSet rs = pst.executeQuery();
            ResultSetMetaData rss = rs.getMetaData();
            DefaultTableModel df = (DefaultTableModel) TeacherTable.getModel();
            df.setRowCount(0);
            while (rs.next()) {   
                
                String id = rs.getString("id");
                String yearString = rs.getString("year");
                String termString = rs.getString("term");
                String banglaString = rs.getString("bangla");
                String englishString = rs.getString("english");
                String mathString = rs.getString("math");
                String scienceString = rs.getString("science");
                String religionString = rs.getString("religion");
                String socialString = rs.getString("social");
                 
                String tbData[] = {id,yearString,termString,banglaString,englishString,mathString,scienceString,religionString,socialString};
                df.addRow(tbData);
                
            }
        } catch (SQLException ex) {
            Logger.getLogger(TeacherList.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }
    private void updateBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updateBtnMouseEntered
        // TODO add your handling code here:
        updateBtn.setBackground(Color.decode("#1417f2"));
    }//GEN-LAST:event_updateBtnMouseEntered

    private void updateBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updateBtnMouseExited
        // TODO add your handling code here:
         updateBtn.setBackground(Color.decode("#4648eb"));
    }//GEN-LAST:event_updateBtnMouseExited

    private void updateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBtnActionPerformed
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            update = con.prepareStatement("UPDATE Result SET year=?,term=?,bangla=?,english=?,math=?,science=?,religion=?,social=? WHERE id=?");
            update.setString(1, yearBox.getSelectedItem().toString());
            update.setString(2, termBox.getSelectedItem().toString());
            update.setString(3, banglaTxt.getText());
            update.setString(4, englishTxt.getText());
            update.setString(5, mathTxt.getText());
            update.setString(6, scienceTxt.getText());
            update.setString(7, religionTxt.getText());
            update.setString(8, socialTxt.getText());
            update.setString(9, id);
            int k = update.executeUpdate();
            if(k ==1){
            clearTxt();
            JOptionPane.showMessageDialog(this, "Record Updated");
            tableLoad();
            
            }
            else{
                clearTxt();
                JOptionPane.showMessageDialog(this, "Update Failed");
                tableLoad();
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(ChangeSyllabus.class.getName()).log(Level.SEVERE, null, ex);
        }
      
    }//GEN-LAST:event_updateBtnActionPerformed

    private void cancelBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelBtnMouseExited
        // TODO add your handling code here:
         
        cancelBtn.setBackground(Color.decode("#4648eb"));
    }//GEN-LAST:event_cancelBtnMouseExited

    private void cancelBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelBtnMouseEntered
        // TODO add your handling code here:
        cancelBtn.setBackground(Color.decode("#1417f2"));
    }//GEN-LAST:event_cancelBtnMouseEntered

    private void cancelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelBtnActionPerformed
        // TODO add your handling code here:
        new AdminUserInterface().setVisible(true);
        this.setVisible(false);
        clearTxt();
    }//GEN-LAST:event_cancelBtnActionPerformed

    private void AddBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddBtnMouseExited
        // TODO add your handling code here:
        AddBtn.setBackground(Color.decode("#4648eb"));
 
    }//GEN-LAST:event_AddBtnMouseExited

    private void AddBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddBtnMouseEntered
        // TODO add your handling code here:
        AddBtn.setBackground(Color.decode("#1417f2"));
    }//GEN-LAST:event_AddBtnMouseEntered

    private void AddBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddBtnActionPerformed
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            add  = (PreparedStatement) con.prepareStatement("insert into Result (id,year,term,bangla,english,math,science,religion,social) Values (?,?,?,?,?,?,?,?,?)");
            add.setString(1, stdIDBox.getSelectedItem().toString());
            add.setString(2, yearBox.getSelectedItem().toString());
            add.setString(3, termBox.getSelectedItem().toString());
            add.setString(4, banglaTxt.getText());
            add.setString(5, englishTxt.getText());
            add.setString(6, mathTxt.getText());
            add.setString(7, scienceTxt.getText());
            add.setString(8, religionTxt.getText());
            add.setString(9, socialTxt.getText());
            int k  = add.executeUpdate();
            if(k == 1){
                JOptionPane.showMessageDialog(this, "Result Added");
                clearTxt();
                tableLoad();
            }
            else{
                
                JOptionPane.showMessageDialog(this, "Error");
                
            }
        } catch (SQLException ex) {
            Logger.getLogger(Teacher.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_AddBtnActionPerformed

    private void deleteBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteBtnMouseExited
        // TODO add your handling code here:
        deleteBtn.setBackground(Color.decode("#4648eb"));

    }//GEN-LAST:event_deleteBtnMouseExited

    private void deleteBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteBtnMouseEntered
        // TODO add your handling code here:
        deleteBtn.setBackground(Color.decode("#1417f2"));
    }//GEN-LAST:event_deleteBtnMouseEntered

    private void deleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBtnActionPerformed
        // TODO add your handling code here:
            try {
            // TODO add your handling code here:
            pst = (PreparedStatement) con.prepareStatement("delete from Result where id=?");
            pst.setString(1, id);
            
            
            int k = pst.executeUpdate();
            if(k == 1){
                clearTxt();
                JOptionPane.showMessageDialog(this, "Record Deleted");
                tableLoad();
            }
            else{
                clearTxt();
                JOptionPane.showMessageDialog(this, "Delete Failed");
                tableLoad();
                
            }
        } catch (SQLException ex) {
            Logger.getLogger(AdminNoticeList.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_deleteBtnActionPerformed

    private void mathTxtFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_mathTxtFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_mathTxtFocusGained

    private void mathTxtFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_mathTxtFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_mathTxtFocusLost

    private void mathTxtMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mathTxtMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_mathTxtMousePressed

    private void mathTxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mathTxtMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_mathTxtMouseClicked

    private void mathTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mathTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mathTxtActionPerformed

    private void englishTxtFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_englishTxtFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_englishTxtFocusGained

    private void englishTxtFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_englishTxtFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_englishTxtFocusLost

    private void englishTxtMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_englishTxtMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_englishTxtMousePressed

    private void englishTxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_englishTxtMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_englishTxtMouseClicked

    private void englishTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_englishTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_englishTxtActionPerformed

    private void socialTxtFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_socialTxtFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_socialTxtFocusGained

    private void socialTxtFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_socialTxtFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_socialTxtFocusLost

    private void socialTxtMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_socialTxtMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_socialTxtMousePressed

    private void socialTxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_socialTxtMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_socialTxtMouseClicked

    private void socialTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_socialTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_socialTxtActionPerformed

    private void banglaTxtFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_banglaTxtFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_banglaTxtFocusGained

    private void banglaTxtFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_banglaTxtFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_banglaTxtFocusLost

    private void banglaTxtMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_banglaTxtMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_banglaTxtMousePressed

    private void banglaTxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_banglaTxtMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_banglaTxtMouseClicked

    private void banglaTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_banglaTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_banglaTxtActionPerformed

    private void searchTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchTxtActionPerformed

    private void searchTxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchTxtKeyReleased
        DefaultTableModel table = (DefaultTableModel) TeacherTable.getModel();
        String search = searchTxt.getText();
        TableRowSorter<DefaultTableModel>tr = new TableRowSorter<DefaultTableModel>(table);
        TeacherTable.setRowSorter(tr);
        tr.setRowFilter(RowFilter.regexFilter(search));
    }//GEN-LAST:event_searchTxtKeyReleased

    private void TeacherTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TeacherTableMouseClicked
        // TODO add your handling code here:
        DefaultTableModel d=  (DefaultTableModel)TeacherTable.getModel();
        int selectedindex = TeacherTable.getSelectedRow();
        if(TeacherTable.getRowSorter()!= null){
            selectedindex = TeacherTable.getRowSorter().convertRowIndexToModel(selectedindex);

        }
        id = d.getValueAt(selectedindex, 0).toString();
        String year = d.getValueAt(selectedindex, 1).toString();
        String term = d.getValueAt(selectedindex, 2).toString();
        String bangla = d.getValueAt(selectedindex, 3).toString();
        String english = d.getValueAt(selectedindex, 4).toString();
        String math = d.getValueAt(selectedindex, 5).toString();
        String science = d.getValueAt(selectedindex, 6).toString();
        String religion = d.getValueAt(selectedindex, 7).toString();
        String social = d.getValueAt(selectedindex, 8).toString();
        
        stdIDBox.setSelectedItem(id);
        yearBox.setSelectedItem(year);
        termBox.setSelectedItem(term);
        banglaTxt.setText(bangla);
        englishTxt.setText(english);
        mathTxt.setText(math);
        scienceTxt.setText(science);
        religionTxt.setText(religion);
        socialTxt.setText(social);

        
    }//GEN-LAST:event_TeacherTableMouseClicked

    private void scienceTxtFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_scienceTxtFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_scienceTxtFocusGained

    private void scienceTxtFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_scienceTxtFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_scienceTxtFocusLost

    private void scienceTxtMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_scienceTxtMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_scienceTxtMousePressed

    private void scienceTxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_scienceTxtMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_scienceTxtMouseClicked

    private void scienceTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_scienceTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_scienceTxtActionPerformed

    private void religionTxtFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_religionTxtFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_religionTxtFocusGained

    private void religionTxtFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_religionTxtFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_religionTxtFocusLost

    private void religionTxtMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_religionTxtMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_religionTxtMousePressed

    private void religionTxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_religionTxtMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_religionTxtMouseClicked

    private void religionTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_religionTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_religionTxtActionPerformed
 
    
    
    
    public void clearTxt(){
        
        scienceTxt.setText("");
        religionTxt.setText("");
        stdIDBox.setSelectedIndex(-1);
        yearBox.setSelectedIndex(-1);
        termBox.setSelectedIndex(-1);
        socialTxt.setText("");
        mathTxt.setText("");
        banglaTxt.setText("");
        englishTxt.setText("");
        //IDLoad();
          
          
    }
    

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ResultPublish.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ResultPublish.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ResultPublish.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ResultPublish.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ResultPublish().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddBtn;
    private javax.swing.JTable TeacherTable;
    private javax.swing.JTextField banglaTxt;
    private javax.swing.JButton cancelBtn;
    private javax.swing.JButton deleteBtn;
    private javax.swing.JTextField englishTxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JTextField mathTxt;
    private javax.swing.JTextField religionTxt;
    private javax.swing.JTextField scienceTxt;
    private javax.swing.JTextField searchTxt;
    private javax.swing.JTextField socialTxt;
    private javax.swing.JComboBox<String> stdIDBox;
    private javax.swing.JComboBox<String> termBox;
    private javax.swing.JButton updateBtn;
    private javax.swing.JComboBox<String> yearBox;
    // End of variables declaration//GEN-END:variables
}
